databases:
  - name: rails_firebase_auth_db
    databaseName: rails_firebase_auth_production
    user: postgre

services:
  - type: web
    name: rails_firebase_auth
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_firebase_auth_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
